export interface ApiSchoolsParams {
  fields: string[];
  pageNumber?: number;
  pageSize?: number;
}

export interface SchoolData {
  schoolId: number
  shortName: string
  longName: string
  schoolType: string
  primaryCategory: string
  address: string
  city: string
  state: string
  zip: number
  phone: string
  fax: string
  cpsSchoolProfile: string
  website: string
  progressReportYear: number
  blueRibbonAwardYear: number
  excelerateAwardGoldYear: number
  spotLightAwardYear: number
  improvementAwardYear: number
  excellenceAwardYear: number
  studentGrowthRating: string
  studentGrowthDescription: string
  growthReadingGradesTested: string
  growthReadingGradesTested1: string
  growthMathGradesTested: string
  growthMathGradesTested1: string
  studentAttainmentRating: string
  studentAttainmentDescription: string
  attainmentReadingPctEs: string
  attainmentReadingLblEs: string
  attainmentMathPctEs: string
  attainmentMathLblEs: string
  cultureClimateRating: string
  cultureClimateDescription: string
  schoolSurveyStudentResponse: number
  schoolSurveyStudentResponse1: number
  schoolSurveyTeacherResponse: number
  schoolSurveyTeacherResponse1: number
  schoolSurveyParentResponse: string
  schoolSurveyParentResponse1: string
  healthySchoolCertification: string
  healthySchoolCertification1: string
  creativeSchoolCertification: string
  creativeSchoolCertification1: string
  nweaReadingGrowthGrade: string
  nweaReadingGrowthGrade1: string
  nweaReadingGrowthGrade2: string
  nweaReadingGrowthGrade3: string
  nweaReadingGrowthGrade4: string
  nweaReadingGrowthGrade5: string
  nweaReadingGrowthGrade6: string
  nweaReadingGrowthGrade7: string
  nweaReadingGrowthGrade8: string
  nweaReadingGrowthGrade9: string
  nweaReadingGrowthGrade10: string
  nweaReadingGrowthGrade11: string
  nweaMathGrowthGrade3: string
  nweaMathGrowthGrade31: string
  nweaMathGrowthGrade4: string
  nweaMathGrowthGrade41: string
  nweaMathGrowthGrade5: string
  nweaMathGrowthGrade51: string
  nweaMathGrowthGrade6: string
  nweaMathGrowthGrade61: string
  nweaMathGrowthGrade7: string
  nweaMathGrowthGrade71: string
  nweaMathGrowthGrade8: string
  nweaMathGrowthGrade81: string
  nweaReadingAttainmentGrade: string
  nweaReadingAttainmentGrade1: string
  nweaReadingAttainmentGrade2: string
  nweaReadingAttainmentGrade3: string
  nweaReadingAttainmentGrade4: string
  nweaReadingAttainmentGrade5: string
  nweaReadingAttainmentGrade6: string
  nweaReadingAttainmentGrade7: string
  nweaReadingAttainmentGrade8: string
  nweaReadingAttainmentGrade9: string
  nweaReadingAttainmentGrade10: string
  nweaReadingAttainmentGrade11: string
  nweaReadingAttainmentGrade12: string
  nweaReadingAttainmentGrade13: string
  nweaMathAttainmentGrade: string
  nweaMathAttainmentGrade1: string
  nweaMathAttainmentGrade2: string
  nweaMathAttainmentGrade3: string
  nweaMathAttainmentGrade4: string
  nweaMathAttainmentGrade5: string
  nweaMathAttainmentGrade6: string
  nweaMathAttainmentGrade7: string
  nweaMathAttainmentGrade8: string
  nweaMathAttainmentGrade9: string
  nweaMathAttainmentGrade10: string
  nweaMathAttainmentGrade11: string
  nweaMathAttainmentGrade12: string
  nweaMathAttainmentGrade13: string
  schoolSurveyInvolved: string
  schoolSurveySupportive: string
  schoolSurveyAmbitious: string
  schoolSurveyEffective: string
  schoolSurveyCollaborative: string
  schoolSurveySafety: string
  suspensionsPer100Students: number
  suspensionsPer100Students1: number
  suspensionsPer100Students2: number
  misconductsToSuspensions: number
  misconductsToSuspensions1: number
  misconductsToSuspensions2: number
  averageLengthSuspension: string
  averageLengthSuspension1: string
  averageLengthSuspension2: string
  behaviorDisciplineYear: number
  behaviorDisciplineYear1: number
  schoolSurveySchoolCommunity: string
  schoolSurveyParentTeacher: string
  schoolSurveyQualityOf: string
  studentAttendanceYear1: number
  studentAttendanceYear2: number
  studentAttendanceAvgPct: number
  teacherAttendanceYear1: number
  teacherAttendanceYear2: number
  teacherAttendanceAvgPct: number
  oneYearDropoutRateYear: number
  oneYearDropoutRateYear1: number
  oneYearDropoutRateAvg: number
  otherMetricsYear1: number
  otherMetricsYear2: number
  freshmenOnTrackSchool: number
  freshmenOnTrackCpsPct: number
  freshmenOnTrackSchool1: number
  freshmenOnTrackCpsPct1: number
  graduation4YearSchool: number
  graduation4YearCpsPct: number
  graduation4YearSchool1: number
  graduation4YearCpsPct1: number
  graduation5YearSchool: number
  graduation5YearCpsPct: number
  graduation5YearSchool1: number
  graduation5YearCpsPct1: number
  collegeEnrollmentSchool: number
  collegeEnrollmentCpsPct: number
  collegeEnrollmentSchool1: number
  collegeEnrollmentCpsPct1: number
  collegePersistenceSchool: number
  collegePersistenceCpsPct: number
  collegePersistenceSchool1: number
  collegePersistenceCpsPct1: number
  progressTowardGraduation: number
  progressTowardGraduation1: number
  stateSchoolReportCard: string
  mobilityRatePct: number
  chronicTruancyPct: number
  emptyProgressReportMessage: string
  schoolSurveyRating: string
  supportiveSchoolAward: string
  supportiveSchoolAwardDesc: string
  parentSurveyResultsYear: number
  schoolLatitude: number
  schoolLongitude: number
  location: { latitude: number; longitude: number }
  psatGrade9ScoreSchool: string
  psatGrade10ScoreSchool: string
  satGrade11ScoreSchool: number
  satGrade11ScoreCpsAvg: number
  growthPsatGrade9School: string
  growthPsatGrade9School1: string
  growthPsatReadingGrade: string
  growthPsatReadingGrade1: string
  growthSatGrade11School: string
  growthSatGrade11School1: string
  attainmentPsatGrade9School: string
  attainmentPsatGrade9School1: string
  attainmentPsatGrade10: string
  attainmentPsatGrade101: string
  attainmentSatGrade11School: string
  attainmentSatGrade11School1: string
  attainmentAllGradesSchool: string
  attainmentAllGradesSchool1: string
  growthPsatMathGrade10: string
  growthPsatMathGrade101: string
  growthSatReadingGrade: string
  growthSatReadingGrade1: string
  growthSatMathGrade11: string
  growthSatMathGrade111: string
}

export type SchoolsDataResponse = SchoolData[];
